# List of active ingredients and diseases they treat (including alternatives)
active_ingredients_list = [
    ('Diazepam', 'Paroxysmal Positional Vertigo', 'AIDS', 'Bronchial Asthma'),
    ('Lamivudine', 'AIDS', 'Hepatitis B', 'Hepatitis C'),
    ('Benzoyl Peroxide', 'Acne', 'Psoriasis'),
    ('Salbutamol (Albuterol)', 'Bronchial Asthma', 'Chronic Obstructive Pulmonary Disease', 'Bronchitis'),
    ('Ibuprofen', 'Cervical Spondylosis', 'Osteoarthritis', 'Migraine'),
    ('Calamine Lotion', 'Chicken Pox', 'Sunburn'),
    ('Ursodeoxycholic Acid', 'Chronic Cholestasis'),
    ('Paracetamol (Acetaminophen)', 'Common Cold', 'Headache', 'Body Aches'),
    ('Chloroquine', 'Dengue', 'Malaria'),
    ('Metformin', 'Diabetes', 'Type 2 Diabetes'),
    ('Gabapentin', 'Diabetic Neuropathy', 'Neuropathic Pain'),
    ('Loperamide (Imodium)', 'Diarrhea', 'Gastroenteritis'),
    ('Hydrocortisone', 'Dimorphic Hemorrhoids (Piles)', 'Skin Inflammation'),
    ('Prednisone', 'Drug Reaction', 'Autoimmune Diseases'),
    ('Fluconazole', 'Fungal Infection', 'Candidiasis'),
    ('Omeprazole', 'GERD', 'Stomach Ulcer'),
    ('Oral Rehydration Salts (ORS)', 'Gastroenteritis'),
    ('Aspirin', 'Heart Attack', 'Stroke'),
    ('Enalapril', 'Hypertension', 'Heart Failure'),
    ('Levothyroxine', 'Hypothyroidism', 'Goiter'),
    ('Glucagon', 'Hypoglycemia'),
    ('Mupirocin', 'Impetigo', 'Skin Infections'),
    ('Liver Supplements (Milk Thistle)', 'Jaundice'),
    ('Artemisinin-based Combination Therapy (ACT)', 'Malaria'),
    ('Sumatriptan', 'Migraine'),
    ('Tissue Plasminogen Activator (tPA)', 'Paralysis (Brain Hemorrhage)', 'Stroke'),
    ('Azithromycin', 'Pneumonia', 'Respiratory Infections'),
    ('Topical Corticosteroids', 'Psoriasis', 'Eczema'),
    ('Rifampicin', 'Tuberculosis', 'Leprosy'),
    ('Ciprofloxacin', 'Typhoid', 'Urinary Tract Infection'),
    ('Nitrofurantoin', 'Urinary Tract Infection'),
    ('Compression Stockings', 'Varicose Veins'),
    ('Hepatitis A Vaccine', 'Hepatitis A'),
    ('Amoxicillin', 'Bacterial Infections', 'Sinusitis', 'Ear Infections'),
    ('Simvastatin', 'High Cholesterol', 'Cardiovascular Disease'),
    ('Furosemide', 'Hypertension', 'Edema', 'Heart Failure'),
    ('Metoclopramide', 'Gastritis', 'Indigestion'),
    ('Ciprofloxacin', 'Urinary Tract Infections', 'Bacterial Infections'),
    ('Losartan', 'Hypertension', 'Chronic Kidney Disease'),
    ('Prednisone', 'Autoimmune Diseases', 'Allergic Reactions', 'Inflammation'),
    ('Bupropion', 'Depression', 'Smoking Cessation'),
    ('Warfarin', 'Blood Clots', 'Atrial Fibrillation'),
    ('Levocetirizine', 'Allergic Rhinitis', 'Hay Fever'),
    ('Tamsulosin', 'Benign Prostatic Hyperplasia', 'Urinary Retention'),
    ('Alendronate', 'Osteoporosis', 'Bone Health'),
    ('Corticosteroids', 'Allergic Reactions', 'Asthma', 'Psoriasis'),
    ('Doxycycline', 'Bacterial Infections', 'Acne', 'Malaria', 'Lyme Disease'),
    ('Lorazepam', 'Anxiety', 'Stress', 'Insomnia'),
    ('Zinc Supplements', 'Immune System Support', 'Common Cold', 'Skin Health'),
    ('Vitamin B12', 'Fatigue', 'Anemia', 'Nerve Disorders'),
    ('Clotrimazole', 'Fungal Infections', 'Athlete’s Foot', 'Vaginal Yeast Infection'),
    ('Tetracycline', 'Bacterial Infections', 'Acne', 'Rosacea', 'Cholera'),
    ('Salbutamol (Albuterol)', 'Asthma', 'Chronic Obstructive Pulmonary Disease (COPD)', 'Bronchitis'),
    ('Doxazosin', 'Hypertension', 'Benign Prostatic Hyperplasia'),
    ('Sodium Chloride (Saline Solution)', 'Nasal Congestion', 'Hydration', 'Eye Irritation'),
]

# Define alternative treatments for diseases
alternatives = {
    'Paroxysmal Positional Vertigo': ['Diazepam', 'Betahistine'],
    'AIDS': ['Lamivudine', 'Tenofovir'],
    'Acne': ['Benzoyl Peroxide', 'Tretinoin', 'Salicylic Acid'],
    'Bronchial Asthma': ['Salbutamol (Albuterol)', 'Ipratropium Bromide', 'Fluticasone'],
    'Osteoarthritis': ['Ibuprofen', 'Paracetamol (Acetaminophen)', 'Diclofenac'],
    'Migraine': ['Sumatriptan', 'Paracetamol (Acetaminophen)', 'Ibuprofen'],
    'Chronic Cholestasis': ['Ursodeoxycholic Acid', 'Silymarin'],
    'Diabetes': ['Metformin', 'Insulin'],
    'Diabetic Neuropathy': ['Gabapentin', 'Pregabalin'],
    'Diarrhea': ['Loperamide (Imodium)', 'Oral Rehydration Salts (ORS)', 'Diphenoxylate'],
    'Fungal Infection': ['Fluconazole', 'Clotrimazole', 'Ketoconazole'],
    'GERD': ['Omeprazole', 'Ranitidine', 'Esomeprazole'],
    'Heart Attack': ['Aspirin', 'Clopidogrel', 'Nitroglycerin'],
    'Hypertension': ['Enalapril', 'Atenolol', 'Losartan'],
    'Hypothyroidism': ['Levothyroxine', 'Liothyronine'],
    'Hypoglycemia': ['Glucagon', 'Dextrose'],
    'Mupirocin': ['Mupirocin', 'Fusidic Acid'],
    'Malaria': ['Artemisinin-based Combination Therapy (ACT)', 'Chloroquine'],
    'Stroke': ['Tissue Plasminogen Activator (tPA)', 'Aspirin'],
    'Pneumonia': ['Azithromycin', 'Amoxicillin', 'Ceftriaxone'],
    'Psoriasis': ['Topical Corticosteroids', 'Calcipotriene', 'Tacrolimus'],
    'Tuberculosis': ['Rifampicin', 'Isoniazid'],
    'Typhoid': ['Ciprofloxacin', 'Azithromycin'],
    'Urinary Tract Infection': ['Ciprofloxacin', 'Nitrofurantoin', 'Amoxicillin'],
    'Varicose Veins': ['Compression Stockings', 'Sclerotherapy'],
    'Hepatitis A': ['Hepatitis A Vaccine'],
    'Sinusitis': ['Amoxicillin', 'Azithromycin'],
    'Rheumatoid Arthritis': ['Ibuprofen', 'Methotrexate'],
    'Leprosy': ['Rifampicin', 'Clofazimine'],
    'Liver Disease': ['Milk Thistle', 'Ursodeoxycholic Acid'],
    'Anemia': ['Vitamin B12', 'Iron Supplements'],
    'Lung Infections': ['Ciprofloxacin', 'Levofloxacin'],
    'Influenza': ['Oseltamivir', 'Zanamivir'],
    'Cholera': ['Tetracycline', 'Doxycycline'],
    'Allergic Rhinitis': ['Levocetirizine', 'Diphenhydramine'],
}
